spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info
    com.cormen.bim: debug
logstash:
  host: localhost