spring:
  datasource:
    url: jdbc:mysql://db:3306/bim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  data:
    mongodb:
      host: mongo
      port: 27017
      database: bim-port
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: #不设置密码
  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /bim
    username: bim
    password: bim
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.cormen.bim: info
logstash:
  host: logstash

