spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bim?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bim-port
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /bim
    username: bim
    password: bim
# 日志配置
logging:
  level:
    root: info
    com.cormen.bim: debug
logstash:
  host: localhost