apiVersion: v1
kind: Service
metadata:
  name: bim-admin-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: bim-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080