apiVersion: v1
kind: Service
metadata:
  name: bim-gateway-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: bim-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8201
      targetPort: 8201
      nodePort: 30201