apiVersion: v1
kind: Service
metadata:
  name: bim-auth-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: bim-auth
  ports:
    - name: http
      protocol: TCP
      port: 8401
      targetPort: 8401